# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
language: r
cache: packages

branches:
  except:
    - gh-pages

apt_packages:
 - libudunits2-dev
 - libgdal-dev
 - libgeos-dev
 - libproj-dev

## Packages not listed as a dependency in DESCRIPTION can be installed here
r_packages:
 - devtools
 - sf
 - tidyverse
 - RMySQL

## A list of packages to install directly from GitHub, using devtools::install_github from the devtools package. The package names here should be of the form user/repo
r_github_packages:
 - emitanaka/xaringan
 - emitanaka/anicon
 - njtierney/ukpolice
 - hadley/babynames
 - jennybc/gapminder

script:
 - Rscript -e "rmarkdown::render('index.Rmd')"

notifications:
  email:
    on_success: change
    on_failure: change

deploy:
  provider: pages
  local_dir: /
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: master
